//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int id_report { get; set; }
        public int request { get; set; }
        public Nullable<System.DateTime> dt_start { get; set; }
        public Nullable<System.DateTime> dt_finish { get; set; }
        public string materials { get; set; }
        public int price { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
