//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Reports = new HashSet<Reports>();
        }
    
        public int id_req { get; set; }
        public int client { get; set; }
        public Nullable<double> serial_number { get; set; }
        public int type_of_eq { get; set; }
        public string description { get; set; }
        public Nullable<int> worker { get; set; }
        public int priority { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> type_of_problem { get; set; }
    
        public string new_client
        {
            get
            {
                return App.context.Users.Where(u => u.id_user == client).Select(u => u.name).FirstOrDefault();
            }
        }
        public string new_worker
        {
            get
            {
                return App.context.Users.Where(u => u.id_user == worker).Select(u => u.name).FirstOrDefault();
            }
        }

        public virtual Priorities Priorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual Statuses_of_request Statuses_of_request { get; set; }
        public virtual Types_of_equipment Types_of_equipment { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Types_of_problem Types_of_problem { get; set; }
    }
}
